name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          cd /path/to/your/application
          # Copy built artifacts from GitHub workspace to Azure VM
          scp -r $GITHUB_WORKSPACE/target/* .
